import bcrypt from "bcrypt";
import { db, adminsTable, agentsTable } from "@workspace/db";
import { eq, sql } from "drizzle-orm";
import { logger } from "./lib/logger";

const agents = [
  {
    slug: "expense-tracker",
    name: "Expense Intelligence Agent",
    shortDescription: "Automatically analyzes weekly spending, identifies financial patterns, and delivers AI-generated expense reports directly to your inbox.",
    description:
      "The Expense Intelligence Agent is an AI-powered financial reporting assistant orchestrated by n8n. It collects expense entries from your Weekly Transaction Repository in Google Sheets, applies Category Classification Logic to organize spending, and runs an AI Spending Analysis Engine to surface meaningful financial patterns. Every week, the agent compiles a comprehensive report — covering totals, category breakdowns, top expenses, and trend monitoring — and delivers it as a ready-to-send email via the Email Reporting Workflow. Results are also returned as an API response for immediate preview in the admin panel.",
    howItWorks:
      "1. A webhook trigger receives expense submissions and appends each entry to the Weekly Transaction Repository in Google Sheets via the Google Sheets Integration.\n2. The workflow filters the current week's entries from the Expense Entry Collection.\n3. Category Classification Logic organizes all transactions by spending type.\n4. The AI Spending Analysis Engine processes the categorized data, identifies financial patterns, and generates Financial Insights.\n5. The Email Reporting Workflow compiles the insights into a structured report and triggers Automated Summary Delivery to the configured inbox.\n6. The completed report is returned as an API response for immediate preview in the admin panel.",
    requirements:
      "Expense Entry Collection, Google Sheets Integration, Weekly Transaction Repository, AI Spending Analysis Engine, Category Classification Logic, Email Reporting Workflow, Financial Insight Generation, Automated Summary Delivery",
    expectedOutput:
      "• Total weekly spend across all categories\n• Per-category expense breakdown with amounts and percentages\n• Top-three expense categories identified and ranked\n• Week-over-week spending trend monitoring\n• Recurring vs. one-time expense identification\n• AI-generated narrative summary of financial activity\n• Spending pattern analysis across categories\n• Ready-to-send email report delivered to configured inbox\n• Category classification for all submitted expense entries\n• Financial insights and observations generated by AI",
    sampleExamples: [
      {
        title: "Weekly Expense Report",
        input: "Expense entries for the week: Food ₹1,200 (4 entries), Transport ₹2,800 (6 entries), Office Supplies ₹4,500 (2 entries), Utilities ₹900 (1 entry), Entertainment ₹1,100 (2 entries).",
        output:
          "Weekly Expense Report\n\nTotal Spend: ₹10,500\n\nTop-3 Categories:\n1. Office Supplies: ₹4,500 (42.9%)\n2. Transport: ₹2,800 (26.7%)\n3. Entertainment: ₹1,100 (10.5%)\n\nFull Breakdown:\n• Food: ₹1,200 (11.4%) — 4 entries\n• Utilities: ₹900 (8.6%) — recurring bill\n\nAI Insights: Office Supplies is the dominant category this week. Transport has 6 trips logged — review for consolidation opportunities. Recurring utilities spend is stable.\n\nReport delivered to configured inbox.",
      },
      {
        title: "Spending Pattern Analysis",
        input: "Four-week transaction history: Week 1 ₹8,200, Week 2 ₹9,400, Week 3 ₹11,800, Week 4 ₹10,500. Categories tracked: Transport, Food, Office Supplies, Utilities, Entertainment.",
        output:
          "Spending Pattern Analysis\n\nAverage Weekly Spend: ₹9,975\nLatest Week vs. Average: +5.3%\n\nTrend Monitoring:\n• Week-over-week trend shows a rise through Week 3 with stabilization in Week 4\n• Transport costs increased consistently across all four weeks\n• Food expenses remain stable with minimal variance\n• Office Supplies shows irregular pattern — likely bulk procurement events\n\nTop-3 recurring categories: Transport, Food, Utilities\n\nAI Insights: Spending is tracking above 4-week average. Transport is the primary growth driver.",
      },
      {
        title: "Executive Summary Email",
        input: "Weekly totals ready for executive delivery: ₹10,500 total, top categories ranked, trend data available, report formatted for inbox.",
        output:
          "Subject: Weekly Expense Intelligence Report\n\nHi,\n\nYour automated weekly expense report is ready.\n\nTotal Spend This Week: ₹10,500\n\nTop-3 Categories:\n1. Office Supplies — ₹4,500 (42.9%)\n2. Transport — ₹2,800 (26.7%)\n3. Entertainment — ₹1,100 (10.5%)\n\nTrend: Spend is 5.3% above the 4-week average of ₹9,975.\n\nAI Observations:\n• Office Supplies is the dominant spend — verify if procurement was planned\n• Transport entries are elevated this week\n• Recurring categories (Utilities, Food) are within normal range\n\nThis is a ready-to-send report generated automatically by the Expense Intelligence Agent.",
      },
    ],
    displayId: "FIN-EXP-001",
    tagline: "Automatically analyzes weekly spending, identifies financial patterns, and delivers AI-generated expense reports directly to your inbox.",
    webhookUrl: "https://n8n.srv1042888.hstgr.cloud/webhook/expense-tracker",
    order: 1,
  },
  {
    slug: "deadline-tracker",
    name: "Task Companion Agent",
    shortDescription: "Automatically monitors pending tasks, prioritizes deadlines, and delivers AI-generated deadline reports directly to your inbox.",
    description:
      "The Task Companion Agent is an AI-powered n8n workflow that integrates with your Google Sheets task repository to deliver intelligent deadline management. It continuously monitors all pending tasks, applies a Deadline Classification Engine to prioritize them by urgency, and generates comprehensive AI-powered deadline reports delivered automatically to your inbox. By combining Pending Task Monitoring with Overdue Task Detection and Priority-Based Task Analysis, the Task Companion Agent transforms your task list into an actionable briefing — ensuring you never miss a critical deadline.",
    howItWorks:
      "1. The agent connects to your Google Sheets task repository via Google Sheets Connectivity and retrieves all active task entries.\n2. The Pending Task Monitoring module filters tasks by status, isolating all incomplete items for analysis.\n3. The Overdue Task Detection engine identifies tasks that have exceeded their deadline, flagging them for immediate attention.\n4. The Deadline Classification Engine applies Priority-Based Task Analysis to rank remaining tasks by urgency and due date.\n5. The AI Report Generation module compiles a comprehensive deadline report, categorizing tasks as Overdue, Due Today, or Upcoming with priority labels.\n6. The completed report is dispatched via Automated Email Delivery to your configured inbox, and an HTML preview is returned as an API response for the admin panel.",
    requirements:
      "Task Repository Integration\nGoogle Sheets Connectivity\nDeadline Classification Engine\nPriority-Based Task Analysis\nPending Task Monitoring\nOverdue Task Detection\nAI Report Generation\nAutomated Email Delivery",
    expectedOutput:
      "• All pending tasks fetched from the connected Google Sheets task repository\n• Tasks classified into Overdue, Due Today, and Upcoming categories by the Deadline Classification Engine\n• Priority labels (High / Medium / Low) applied and preserved across all task entries\n• Overdue tasks detected and flagged for immediate action\n• Priority-Based Task Analysis ranking applied to all active tasks\n• AI-generated deadline report compiled with structured task sections\n• Task count summary per category included in the report\n• Formatted HTML report with clear deadline sections and priority indicators\n• Report delivered automatically to the configured inbox via Automated Email Delivery\n• HTML report preview returned as an API response for admin panel review",
    sampleExamples: [
      {
        title: "Daily Deadline Report",
        input: "Pending tasks retrieved: Finalize project proposal (High, 2026-06-11, Pending), Submit budget review (Medium, 2026-06-14, Pending), Update team documentation (Low, 2026-06-18, Pending), Complete client onboarding (High, 2026-06-09, Pending).",
        output:
          "📋 Daily Deadline Report\n\n🔴 OVERDUE\n• Complete client onboarding — High priority (was due 2026-06-09)\n\n🟠 DUE TODAY\n• Finalize project proposal — High priority (due 2026-06-11)\n\n🟡 UPCOMING\n• Submit budget review — Medium priority (due 2026-06-14)\n• Update team documentation — Low priority (due 2026-06-18)\n\nTask Summary: 1 Overdue | 1 Due Today | 2 Upcoming\n\nReport delivered to configured inbox.",
      },
      {
        title: "Task Categorization",
        input: "Task batch submitted for categorization: Design wireframes (High, 2026-06-13, Pending), Code review session (Medium, 2026-06-11, Pending), Update dependencies (Low, 2026-06-07, Pending), Prepare sprint notes (Medium, 2026-06-16, Pending).",
        output:
          "📂 Task Categorization Report\n\nDeadline Classification Engine Results:\n\n🔴 OVERDUE (1)\n• Update dependencies — Low priority (was due 2026-06-07)\n\n🟠 DUE TODAY (1)\n• Code review session — Medium priority (due 2026-06-11)\n\n🟡 UPCOMING (2)\n• Design wireframes — High priority (due 2026-06-13)\n• Prepare sprint notes — Medium priority (due 2026-06-16)\n\nPriority-Based Analysis: 1 High | 2 Medium | 1 Low\n\nAll tasks classified and report dispatched.",
      },
      {
        title: "Executive Summary",
        input: "End-of-day summary requested: 8 total pending tasks across all priorities. 2 overdue, 1 due today, 5 upcoming. Report ready for executive delivery.",
        output:
          "Subject: Task Companion Agent — Daily Deadline Summary\n\nHi,\n\nYour automated daily deadline report is ready.\n\nTask Overview:\n• Total Pending Tasks: 8\n• 🔴 Overdue: 2 tasks requiring immediate attention\n• 🟠 Due Today: 1 task\n• 🟡 Upcoming: 5 tasks\n\nPriority Breakdown:\n• High Priority: 3 tasks\n• Medium Priority: 3 tasks\n• Low Priority: 2 tasks\n\nAI Observations:\n• 2 overdue tasks detected — immediate action recommended\n• High-priority upcoming tasks should be scheduled for review\n• No blockers identified for tasks due later in the week\n\nThis report was generated automatically by the Task Companion Agent.",
      },
    ],
    displayId: "DL-TRK-001",
    tagline: "Tracks tasks and deadlines from Google Sheets. Filters pending tasks, classifies them as Today / Upcoming / Overdue using AI, and sends a formatted HTML digest email on demand.",
    webhookUrl: "https://n8n.srv1042888.hstgr.cloud/webhook/deadline-tracker",
    order: 2,
  },
  {
    slug: "hr-agent",
    name: "HR Bot",
    shortDescription: "Upload a candidate's PDF resume for instant ATS scoring — degree, keywords, experience, location, and relocation eligibility evaluated in seconds.",
    description:
      "The AI Resume Screening Agent automates the initial candidate evaluation process for AI and machine learning roles. The system analyzes resumes, extracts candidate information, evaluates qualifications against predefined hiring criteria, and generates structured hiring recommendations.\n\nBy eliminating manual resume screening, recruiters can quickly identify high-potential candidates while maintaining a consistent and objective evaluation process across every application.",
    howItWorks:
      "The agent receives candidate resumes and extracts relevant information including contact details, education, experience, location, and AI-related skills.\n\nEach candidate is automatically evaluated against a predefined scoring model that measures:\n• AI/ML educational background\n• LLM experience\n• RAG experience\n• Chatbot development experience\n• Agentic AI experience\n• Generative AI exposure\n• Professional experience level\n• Geographic eligibility\n• Relocation flexibility\n\nAfter scoring, the system assigns a hiring recommendation and routes candidates into appropriate recruitment pipelines.",
    requirements:
      "Resume Upload Capability\nOpenAI GPT Integration\nGoogle Sheets Database\nCandidate Evaluation Framework\nRecruitment Workflow Configuration\nAutomated Email Integration\nATS Scoring Logic\nHiring Decision Thresholds",
    expectedOutput:
      "The agent produces:\n• Candidate profile extraction\n• Contact information identification\n• AI skills assessment\n• Experience evaluation\n• Qualification scorecard\n• ATS compatibility score\n• Hiring recommendation\n• Candidate classification\n• Recruitment tracking records\n• Automated interview invitations",
    sampleExamples: [
      {
        title: "Resume Evaluation Result",
        input: "Candidate resume submitted for evaluation: B.Tech Artificial Intelligence graduate with LLM, RAG, Agent, and GenAI keywords detected.",
        output: JSON.stringify({
          candidate_name: "Rahul Sharma",
          degree_detected: "B.Tech Artificial Intelligence",
          keywords_hit: ["LLM", "RAG", "Agent", "GenAI"],
          total_score: 82,
          status: "Shortlisted"
        }, null, 2),
      },
      {
        title: "Candidate Assessment (Scored 78 / Shortlisted)",
        input: "Resume contains:\n• 3 years AI experience\n• RAG applications\n• LLM projects\n• Mumbai location",
        output: JSON.stringify({
          total_score: 78,
          status: "Shortlisted"
        }, null, 2),
      },
      {
        title: "Candidate Assessment (Scored 28 / Rejected)",
        input: "Resume contains:\n• General software background\n• No AI projects\n• No GenAI experience",
        output: JSON.stringify({
          total_score: 28,
          status: "Rejected"
        }, null, 2),
      },
    ],
    displayId: "HR-ATS-001",
    tagline: "Automatically evaluates, scores, and shortlists AI candidates using ATS-style screening and hiring intelligence.",
    webhookUrl: "https://hook.eu2.make.com/z3htgslpiry2cvi5cxxa133f2uvcycim",
    order: 3,
  },
  {
    slug: "appointment-booking",
    name: "Business Documentation Agent",
    shortDescription: "AI-powered document automation assistant that generates proposals, contracts, compliance documents, statements of work, and invoices from client requirements.",
    description:
      "The Business Documentation Agent is an AI-powered document automation assistant designed to streamline the creation of professional business documents. By transforming client requirements into structured, ready-to-use deliverables, the agent significantly reduces the time spent preparing proposals, agreements, and commercial documentation.\n\nWhether supporting sales teams, operations teams, consultants, or service providers, the agent ensures consistent, professional, and standardized documentation across every engagement.",
    howItWorks:
      "The agent receives client information, project details, budget requirements, timelines, and requested services through an intake workflow.\n\nThe submitted request is analyzed and classified to determine the appropriate document type. Based on the business context, the agent generates professional documents using predefined structures and compliance-focused templates.\n\nGenerated documents are formatted for immediate business use and can be stored, reviewed, or delivered through integrated document management systems.",
    requirements:
      "Client Intake Workflow, Service Classification Engine, Proposal Generation Framework, Contract Template Repository, Compliance Documentation Engine, Invoice Creation Workflow, Google Drive Integration, AI Document Generation System.",
    expectedOutput:
      "The Business Documentation Agent generates: Professional Services Proposals, Statements of Work (SOW), Non-Disclosure Agreements (NDA), Data Processing Agreements (DPA), Commercial Invoices, Client Engagement Documentation, Project Scope Documents, Service Delivery Agreements, Compliance Documentation, Business Contract Templates.",
    sampleExamples: [
      {
        title: "Proposal Generation",
        input: "Client requests an AI chatbot implementation project with a six-week timeline and a defined budget.",
        output:
          "Professional Services Proposal\n\nClient: ABC Technologies\n\nExecutive Summary\nThis proposal outlines the implementation of an AI-powered customer support solution designed to improve response times and customer satisfaction.\n\nScope of Work\n• AI Chatbot Development\n• Knowledge Base Integration\n• User Acceptance Testing\n• Deployment Support\n\nTimeline\n6 Weeks\n\nCommercials\nProject Fee: ₹4,50,000\n\nNext Steps\nProject kickoff upon approval.",
      },
      {
        title: "NDA Generation",
        input: "Client requests confidentiality documentation before project discussions.",
        output:
          "Mutual Non-Disclosure Agreement\n\nThis Agreement is entered into between the Parties for the purpose of evaluating potential business collaboration.\n\nConfidential Information\nAll technical, commercial, financial, and proprietary information shared during discussions shall remain confidential.\n\nTerm\nTwo years from the Effective Date.",
      },
      {
        title: "Invoice Generation",
        input: "Approved project with milestone-based billing.",
        output:
          "Invoice No: INV-2026-001\n\nProfessional Services\nAI Automation Consulting\n\nMilestone 1: 30%\nMilestone 2: 40%\nMilestone 3: 30%\n\nTotal Amount: ₹3,00,000\n\nPayment Terms:\nNet 15 Days",
      },
    ],
    displayId: "DOC-AUTO-001",
    tagline: "Automatically generates proposals, contracts, compliance documents, and commercial paperwork from client requirements.",
    webhookUrl: "https://n8n.srv1042888.hstgr.cloud/webhook/appointment-booking",
    order: 4,
  },
  {
    slug: "customer-support",
    name: "Help Desk Agent",
    shortDescription: "AI-powered customer support assistant that classifies inquiries, retrieves relevant information, and automatically generates professional email responses.",
    description:
      "The Help Desk Agent is an AI-powered support assistant designed to streamline customer communication and improve response times. By monitoring incoming emails, understanding customer intent, and generating context-aware replies, the agent ensures every inquiry receives timely and professional attention.\nWhether customers have billing questions, product-related concerns, or general inquiries, the agent intelligently categorizes requests and provides appropriate responses while maintaining a consistent support experience.",
    howItWorks:
      "The agent continuously monitors incoming customer emails and analyzes each message using AI-powered intent detection.\nBased on the content of the email, the system automatically categorizes inquiries into billing and financial questions, product-related concerns, or general support requests. For specialized inquiries, the agent retrieves relevant information from connected knowledge sources and generates an accurate, professional response.\nThe completed response is then automatically delivered to the customer via email, ensuring consistent communication and reduced support workload.",
    requirements:
      "Gmail integration\nIncoming email monitoring\nCustomer support knowledge base\nFinancial policy knowledge repository\nProduct support documentation\nOpenAI language model access\nAutomated email response system\nCustomer communication workflows",
    expectedOutput:
      "The Help Desk Agent generates:\n• Automated customer email responses\n• Billing and refund assistance\n• Product support acknowledgments\n• General inquiry responses\n• Customer issue classification\n• Knowledge-based support answers\n• Professional email communications\n• Support request routing\n• AI-generated customer assistance\n• Consistent brand-aligned responses",
    displayId: "CS-CARE-001",
    tagline: "Automatically understands customer inquiries, routes them intelligently, and delivers professional support responses in real time.",
    sampleExamples: [
      {
        title: "Billing Inquiry",
        input: "I cancelled my subscription and would like to know when my refund will be processed.",
        output:
          "Hello Rahul,\n\nThank you for reaching out.\n\nRefunds for eligible cancelled subscriptions are typically processed within 5–7 business days after confirmation. Once the refund has been initiated, you will receive a confirmation email with additional details.\n\nPlease let us know if you have any further questions.\n\nBest regards,\nTechNEo Solutions Support Team",
      },
      {
        title: "Product Support Request",
        input: "I'm unable to connect your platform with Slack. Is there an issue with the integration?",
        output:
          "Hello,\n\nThank you for contacting us.\n\nWe understand you are experiencing an issue with the Slack integration. Our technical support team has been notified and will investigate the matter. A specialist will reach out within 24 hours to assist further.\n\nBest regards,\nTechNEo Solutions Support Team",
      },
      {
        title: "General Inquiry",
        input: "I would like to learn more about your enterprise offerings.",
        output:
          "Hello,\n\nThank you for your interest in our services.\n\nYour inquiry has been forwarded to the appropriate team, and someone will be in touch shortly with additional information regarding our enterprise solutions.\n\nBest regards,\nTechNEo Solutions Support Team",
      },
    ],
    order: 5,
  },
  {
    slug: "campus-concierge",
    name: "Campus Concierge Agent",
    shortDescription: "Your intelligent university assistant — schedules, resources, events, and campus navigation in one place.",
    description:
      "The Campus Concierge Agent is a comprehensive assistant for students, faculty, and staff. It helps navigate campus resources, answers questions about policies and procedures, assists with course registration, facility bookings, event discovery, and provides personalized recommendations based on your academic profile.",
    howItWorks:
      "The agent integrates with university systems (SIS, LMS, facility management, event calendars) and provides a unified interface for all campus needs. It understands academic calendars, knows building locations, and can handle complex multi-step tasks like finding study rooms with available equipment near your next class.",
    requirements:
      "University SIS integration, campus map and facility database, event management system access, student/faculty profile data (with privacy controls), academic calendar configuration.",
    expectedOutput:
      "Course schedules and registration assistance, facility and room bookings, event recommendations, campus navigation directions, policy answers, deadline reminders, and resource availability status.",
    sampleExamples: [
      {
        title: "Study Room Booking",
        input: "I need a quiet study room for 4 people with a projector for tomorrow afternoon.",
        output:
          "Found 3 options for tomorrow 12-6PM: (1) Library Room 204 — projector, whiteboard, available 1-5PM. (2) Engineering Building B-12 — 4K display, standing desks, available 2-6PM. (3) Student Union Meeting Room 3 — projector, free coffee station, available 1-4PM. Booking Library Room 204 for 2-5PM? I'll send calendar invites to your group.",
      },
      {
        title: "Course Registration Help",
        input: "What courses can I take next semester that fulfill my CS major requirements?",
        output:
          "Based on your transcript, you still need: 1 algorithms course, 1 systems course, 2 CS electives. Available next semester that fit: CS401 (Advanced Algorithms, MWF 10am — Prof. Lee, 4.8 rating), CS415 (Operating Systems, TTh 2pm), CS450 (Machine Learning, MWF 2pm — HIGHLY recommended for your AI track). Registration opens Nov 1 for your class year. Want me to add these to your watchlist?",
      },
    ],
    displayId: "EDU-CAMP-001",
    tagline: "Your intelligent university assistant — schedules, resources, events, and campus navigation unified in one place.",
    webhookUrl: "https://n8n.srv1042888.hstgr.cloud/webhook/campus-concierge",
    order: 6,
  },
  {
    slug: "hospital-receptionist",
    name: "Hospital Receptionist Agent",
    shortDescription:
      "AI-powered virtual receptionist that assists patients with appointment scheduling, rescheduling, cancellations, doctor information, and hospital support services.",
    description:
      "AI-powered voice receptionist for MediCare Hospital. Patients call to look up their records, book new appointments, check upcoming visits, cancel or reschedule — all through natural conversation. Powered by Retell AI voice platform with n8n workflow automation and NocoDB patient database.",
    howItWorks:
      "The Hospital Receptionist Agent answers inbound patient calls and identifies the caller's request.\n\nFor appointment bookings, the agent collects patient information, appointment preferences, and visit details before creating a confirmed booking. Patients may also request a booking link through email.\n\nFor appointment modifications, the agent verifies identity using the patient's phone number, retrieves existing appointments, and performs rescheduling or cancellation actions as requested.\n\nThe agent also provides general hospital information, doctor availability details, operating hours, and location guidance. If a request requires additional support, the caller can be transferred to a human receptionist.",
    requirements:
      "Appointment Scheduling System, Patient Verification Workflow, Doctor Directory Access, Appointment Management Functions, Email Notification Service, Hospital Information Repository, Voice Calling Platform, Human Receptionist Escalation",
    expectedOutput:
      "Appointment booking assistance, Appointment rescheduling, Appointment cancellation, Patient verification, Doctor availability information, Hospital operating hours, Location and contact assistance, Email booking link delivery, Patient support guidance, Human receptionist escalation",
    sampleExamples: [
      {
        title: "Appointment Booking",
        input: "I'd like to book an appointment with a cardiologist.",
        output:
          "Certainly. May I have your full name?\nThank you.\nCould you please provide your phone number?\nWhich date and time would you prefer for the appointment?\nI have successfully booked your appointment with Dr. Prerna Ladkani. A confirmation has been recorded.",
      },
      {
        title: "Appointment Rescheduling",
        input: "I'd like to move my appointment to next Friday.",
        output:
          "I'd be happy to help.\nCould you please provide the phone number associated with your appointment?\nThank you.\nWhich appointment would you like to reschedule and what is your preferred new date and time?\nYour appointment has been successfully rescheduled.",
      },
      {
        title: "General Information",
        input: "What are your hospital timings?",
        output:
          "City Hospital is open Monday through Friday from 8 AM to 6 PM and Saturday from 9 AM to 1 PM.\nThe hospital remains closed on Sundays.",
      },
    ],
    displayId: "HOSP-REC-001",
    tagline: "Provides patients with appointment scheduling, rescheduling, cancellations, doctor information, and hospital assistance through a conversational voice experience.",
    order: 7,
  },
  {
    slug: "linkedin-management",
    name: "LinkedIn Management Multi Agent",
    shortDescription: "Autonomous multi-agent LinkedIn content system — 4 specialized AI agents transform your topic into a polished post, custom visual, and LinkedIn publication with your approval.",
    description:
      "Autonomous multi-agent LinkedIn content system. Submit a topic and 4 specialized AI agents work in sequence: a Structure & Logic Designer builds the teaching blueprint, a Draft Copywriter writes the post, a Style & Compliance Editor polishes it, and an Image Architect generates a custom visual. The final draft is sent to your email for human approval — approve to auto-publish to LinkedIn, or reject to discard. Powered by n8n workflow automation with OpenAI GPT models.",
    howItWorks:
      "The agent begins by retrieving pending content topics from a centralized content repository. It then creates a strategic content framework, identifying the problem, context, core insight, practical recommendations, common mistakes, and desired outcomes associated with the topic. The framework is transformed into a professional LinkedIn post designed to establish authority and encourage engagement. The workflow simultaneously generates visual concepts and image-generation prompts to support the post. Content and visuals are routed through a quality control and approval process before being published directly to LinkedIn. All published assets and statuses are automatically recorded for future reference and reporting.",
    requirements:
      "LinkedIn Integration, Google Sheets Content Repository, Strategic Content Framework Engine, AI Copywriting Workflow, Visual Concept Generation, Image Creation Pipeline, Human Approval Workflow, Automated Publishing System",
    expectedOutput:
      "• LinkedIn thought leadership posts\n• Strategic content frameworks\n• Professional storytelling content\n• Visual content concepts\n• AI image generation prompts\n• Publish-ready social media assets\n• Human approval workflows\n• Automated LinkedIn publishing\n• Content history tracking\n• Content performance preparation",
    displayId: "LINKEDIN-TL-001",
    tagline: "Transforms content ideas into high-quality LinkedIn thought leadership posts, visual concepts, and publish-ready content through an AI-powered content creation workflow.",
    sampleExamples: [
      {
        title: "Thought Leadership Post",
        input: "Why AI projects fail inside enterprises",
        output:
          "Most AI projects don't fail because of technology.\n\nThey fail because organizations mistake experimentation for execution.\n\nThe real challenge begins after the proof of concept...\n• Align business outcomes before selecting models\n• Define ownership early\n• Build adoption plans alongside deployment\n\nThe companies succeeding with AI aren't moving faster.\nThey're executing with more discipline.\n\nWhat do you think is the biggest reason enterprise AI initiatives struggle?",
      },
      {
        title: "Visual Concept Generation",
        input: "Scaling AI Operations",
        output:
          "Visual Concept:\nA modern control tower overlooking multiple AI systems operating across an organization.\n\nSymbolism:\n• Control tower = governance\n• Multiple connected systems = scale\n• Clear visibility = operational maturity\n\nStyle:\nEditorial photography with cinematic lighting and professional business aesthetics.",
      },
      {
        title: "Publishing Workflow",
        input: "Publish approved thought leadership content to LinkedIn.",
        output:
          "Content Status: Approved\nImage Generated: Yes\nPublishing Channel: LinkedIn\nPublication Status: Published Successfully\nContent Logged: Complete",
      },
    ],
    order: 8,
  },
];

async function seed() {
  logger.info("Starting seed...");

  const adminUsername = "admin";
  const adminPassword = "admin123";
  const passwordHash = await bcrypt.hash(adminPassword, 12);

  const [existingAdmin] = await db
    .select()
    .from(adminsTable)
    .where(eq(adminsTable.username, adminUsername));

  if (!existingAdmin) {
    await db.insert(adminsTable).values({ username: adminUsername, passwordHash });
    logger.info({ username: adminUsername }, "Admin created");
  } else {
    logger.info({ username: adminUsername }, "Admin already exists");
  }

  for (const agent of agents) {
    await db
      .insert(agentsTable)
      .values(agent)
      .onConflictDoUpdate({
        target: agentsTable.slug,
        set: {
          name: sql`excluded.name`,
          shortDescription: sql`excluded.short_description`,
          description: sql`excluded.description`,
          howItWorks: sql`excluded.how_it_works`,
          requirements: sql`excluded.requirements`,
          expectedOutput: sql`excluded.expected_output`,
          sampleExamples: sql`excluded.sample_examples`,
          displayId: sql`excluded.display_id`,
          tagline: sql`excluded.tagline`,
          webhookUrl: sql`excluded.webhook_url`,
          order: sql`excluded.order`,
        },
      });
    logger.info({ slug: agent.slug }, "Agent upserted");
  }

  logger.info("Seed complete.");
  process.exit(0);
}

seed().catch((err) => {
  logger.error({ err }, "Seed failed");
  process.exit(1);
});
